backend:
  name: git-gateway
  repo: liminalfun/subversions-hugo
  branch: master

local_backend: true

media_folder: "site/content/resources" # Folder where user uploaded files should go
public_folder: "resources"

i18n:
  structure: multiple_files
  locales: [en, fr]
  default_locale: en

collections: 
  - name: "_index"
    label: "Home"
    folder: "site/content"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "about"
    label: "About Page"
    folder: "site/content/about"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "archive"
    label: "Archive Page"
    folder: "site/content/archive"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "issue"
    label: "Issue Pages"
    label_singular: "Issue"
    folder: "site/content/issue"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "submission"
    label: "Submissions"
    label_singular: "Submission"
    folder: "site/content/submission"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "pdf-issues"
    label: "PDF Issues"
    label_singular: "PDF Issue"
    folder: "site/content/pdf-issues"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "popup"
    label: "Pop-Up Message"
    folder: "site/content/popup"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}
  - name: "settings"
    label: "Site Settings"
    folder: "site/content/settings"
    create: true 
    i18n: true
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: true}